---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/default.yml
    - vault.yml

  tasks:
    # Sudo
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    # User setupd 
    - name: Create admin user 
      user:
        name: "{{ default_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ default_user }}"
        state: present
        key: "{{ ssh_pub_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    # Install Packages
    - name: Add tailscale apt key 
      apt_key:
        url: "{{ tailscale_apt_signkey }}"  
        state: present
      
    - name: Add tailscale repostiory
      apt_repository:
        repo: "{{ tailscale_apt_deb }}"
        state: present
    
    - name: Add Docker apt key 
      apt_key:
        url: "{{ docker_apt_signkey }}" 
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_deb }}" 
        state: present

    - name: Wait for automatic system updates
      become: true
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
      with_items:
        - lock
        - lock-frontend

    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest