---
default_user: jem
ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'tailscale', 'docker-ce']

tailscale_apt_deb: deb https://pkgs.tailscale.com/stable/ubuntu focal main
tailscale_apt_signkey: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg

docker_apt_deb: deb https://download.docker.com/linux/ubuntu focal stable
docker_apt_signkey: https://download.docker.com/linux/ubuntu/gpg