name: deploy 

on:
  push:
    branches: [ "main" ]

jobs:
  pulumi-ansible:
    runs-on: ubuntu-latest
    environment: prod
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps and setup 
        run: |
          npm install
          pulumi login
          pulumi stack select prod

      # - name: Destroy existing stack 
      #   run: make pulumi-destroy
      
      - name: Bring stack up
        run: make pulumi-up

      - name: Wait for droplet to start
        run: sleep 15

      - name: SSH keyscan
        run: ssh-keyscan $(pulumi stack output dropletIp)

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Write vault password
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: echo $VAULT_PASS > ./vault_pass.txt

      - name: Run ansible against relay
        run: make ansible ansible_extra_args="--vault-password-file ./vault_pass.txt"